AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: ECR Continuous Scan

Globals:
  Function:
    Timeout: 30
  Api:
    Cors:
      AllowMethods: "'*'"
      AllowHeaders: "'*'"
      AllowOrigin: "'*'"

Parameters:
    ConfigBucketName:
        Type: String
    AllowIPAddress:
        Type: String

Resources:
  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: dev
      Auth:
        ResourcePolicy:
          CustomStatements: [
            {
              "Effect": "Allow",
              "Principal": "*",
              "Action": "execute-api:Invoke",
              "Resource": "execute-api:/*/*/*",
              "Condition": {
                "IpAddress": {
                  "aws:SourceIp": !Sub "${AllowIPAddress}"
                }
              }
            }
          ]

  ConfigsFunc:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: bin/
      Handler: configs
      Runtime: go1.x
      Tracing: Active
      Environment:
        Variables:
          ECR_SCAN_CONFIG_BUCKET: !Sub "${ConfigBucketName}"
      Events:
        AddConfig:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /configs
            Method: POST
        RemoveConfig:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /configs/{id}
            Method: DELETE
        ListConfigs:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /configs
            Method: GET
      Policies:
        - AWSLambdaExecute
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
              - s3:*
              Resource:
              - !Sub "arn:aws:s3:::${ConfigBucketName}/*"
              - !Sub "arn:aws:s3:::${ConfigBucketName}"
  SummaryFunc:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: bin/
      Handler: summary
      Runtime: go1.x
      Tracing: Active
      Environment:
        Variables:
          ECR_SCAN_CONFIG_BUCKET: !Sub "${ConfigBucketName}"
      Events:
        CatchAll:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /summary
            Method: GET
      Policies:
        - AWSLambdaExecute
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
              - ecr:*
              Resource: '*'
            - Effect: Allow
              Action:
              - s3:*
              Resource:
              - !Sub "arn:aws:s3:::${ConfigBucketName}/*"
              - !Sub "arn:aws:s3:::${ConfigBucketName}"
  FindingsFunc:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: bin/
      Handler: findings
      Runtime: go1.x
      Tracing: Active
      Environment:
        Variables:
          ECR_SCAN_CONFIG_BUCKET: !Sub "${ConfigBucketName}"
      Events:
        CatchAll:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /findings/{id}
            Method: GET
      Policies:
        - AWSLambdaExecute
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
              - ecr:*
              Resource: '*'
            - Effect: Allow
              Action:
              - s3:*
              Resource:
              - !Sub "arn:aws:s3:::${ConfigBucketName}/*"
              - !Sub "arn:aws:s3:::${ConfigBucketName}"
  StartScanFunc:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: bin/
      Handler: start-scan
      Runtime: go1.x
      Tracing: Active
      Environment:
        Variables:
          ECR_SCAN_CONFIG_BUCKET: !Sub "${ConfigBucketName}"
      Events:
        Timer:
          Type: Schedule
          Properties:
            Schedule: cron(0 0 1 * ? *)
      Policies:
        - AWSLambdaExecute
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
              - ecr:*
              Resource: '*'
            - Effect: Allow
              Action:
              - s3:*
              Resource:
              - !Sub "arn:aws:s3:::${ConfigBucketName}/*"
              - !Sub "arn:aws:s3:::${ConfigBucketName}"

Outputs:
  ECRScanAPIEndpoint:
    Description: "The ECR Continuous Scan HTTP API Gateway endpoint URL"
    Value: !Sub "https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/dev"
